"""
run_analysis.py
------------------
End-to-end driver for the fluid-substitution / pre-stack AVO modelling
workflow: builds the synthetic well, performs Gassmann fluid substitution,
builds the rock-physics template, runs the pre-stack synthetic seismic /
AVO modelling, generates every figure used in the README and report, and
writes a machine-readable results summary.

Run from the project root:
    python run_analysis.py
"""

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src import fluid_properties as fl
from src import rock_physics_model as rpm
from src import synthetic_well as sw
from src import rock_physics_template as rpt
from src import avo_modeling as avo
from src import plotting as viz

FIGDIR = ROOT / "figures"
DATADIR = ROOT / "data"
FIGDIR.mkdir(exist_ok=True)
DATADIR.mkdir(exist_ok=True)

# Clean sub-intervals used for representative layer properties (avoid the
# smoothed lithology-boundary transition samples).
SHALE_CAP_ZONE = (2128.0, 2138.0)
RESERVOIR_CLEAN_ZONE = (2142.0, 2154.0)
UNDERLYING_SHALE_ZONE = (2160.0, 2172.0)

OVERBURDEN_AVG_VELOCITY_MPS = 2400.0  # for depth-to-time conversion only
RICKER_FREQUENCY_HZ = 30.0
ANGLES_DEG = np.arange(0, 36, 1)
NEAR_RANGE, MID_RANGE, FAR_RANGE = (0, 12), (12, 24), (24, 35)


def two_way_time(depth_m):
    return 2.0 * depth_m / OVERBURDEN_AVG_VELOCITY_MPS


def sanity_checks(df, results):
    """Lightweight physical-plausibility assertions -- fail loudly rather
    than silently shipping an unphysical result."""
    r = results["reservoir_properties"]
    assert r["GAS"]["vp"] < r["OIL"]["vp"] < r["BRINE"]["vp"], \
        "Expected Vp(gas) < Vp(oil) < Vp(brine) at fixed porosity/frame."
    assert r["GAS"]["rho"] < r["OIL"]["rho"] < r["BRINE"]["rho"], \
        "Expected rho(gas) < rho(oil) < rho(brine)."
    assert r["GAS"]["ai"] < r["OIL"]["ai"] < r["BRINE"]["ai"], \
        "Expected AI(gas) < AI(oil) < AI(brine)."
    assert df["PHIE"].between(0, 0.45).all(), "Porosity out of physical range."
    assert df["VSHALE"].between(0, 1).all(), "Vshale out of [0,1] range."

    # Gassmann round-trip self-consistency check: substituting brine -> brine
    # should be an exact identity.
    idx = df.index[(df["DEPTH_M"] >= RESERVOIR_CLEAN_ZONE[0]) &
                   (df["DEPTH_M"] <= RESERVOIR_CLEAN_ZONE[1])]
    sub = df.loc[idx]
    rt = rpm.gassmann_fluid_substitution(
        sub["VP_BRINE_MPS"].to_numpy(), sub["VS_BRINE_MPS"].to_numpy(),
        sub["RHO_BRINE_KGM3"].to_numpy(), sub["PHIE"].to_numpy(), sub["VSHALE"].to_numpy(),
        sub["K_BRINE_FLUID_PA"].to_numpy(), sub["RHO_BRINE_FLUID_KGM3"].to_numpy(),
        sub["K_BRINE_FLUID_PA"].to_numpy(), sub["RHO_BRINE_FLUID_KGM3"].to_numpy(),
    )
    assert np.allclose(rt["vp"], sub["VP_BRINE_MPS"], rtol=1e-8), "Gassmann round-trip failed (Vp)."
    assert np.allclose(rt["rho"], sub["RHO_BRINE_KGM3"], rtol=1e-8), "Gassmann round-trip failed (rho)."
    print("[ok] All sanity checks passed (fluid ordering, physical ranges, Gassmann round-trip).")


def synthesize_gamma_ray(vshale, seed=11, gr_sand=20.0, gr_shale=115.0, noise_std=3.0):
    from scipy.ndimage import gaussian_filter1d
    rng = np.random.default_rng(seed)
    gr = gr_sand + vshale * (gr_shale - gr_sand)
    noise = gaussian_filter1d(rng.normal(0, 1, size=len(vshale)), sigma=2.0)
    return gr + noise_std * noise / np.std(noise)


def write_las(df, path):
    import lasio
    las = lasio.LASFile()
    las.well.WELL = "SYN-1"
    las.well.FLD = "Synthetic Tertiary Clastic Type-Well"
    las.well.STRT = df["DEPTH_M"].iloc[0]
    las.well.STOP = df["DEPTH_M"].iloc[-1]
    las.well.STEP = df["DEPTH_M"].iloc[1] - df["DEPTH_M"].iloc[0]
    las.well.NULL = -999.25
    las.well.COMP = "Synthetic -- no real operator/company"
    las.params["SRVC"] = lasio.HeaderItem("SRVC", value="Generated by run_analysis.py, this repository")

    gr = synthesize_gamma_ray(df["VSHALE"].to_numpy())
    dt_us_ft = 304_800.0 / df["VP_BRINE_MPS"].to_numpy()

    las.append_curve("DEPT", df["DEPTH_M"].to_numpy(), unit="M")
    las.append_curve("GR", gr, unit="API", descr="Synthesized gamma ray (consistent with Vshale)")
    las.append_curve("VSH", df["VSHALE"].to_numpy(), unit="V/V")
    las.append_curve("PHIE", df["PHIE"].to_numpy(), unit="V/V")
    las.append_curve("RHOB", df["RHO_BRINE_KGM3"].to_numpy() / 1000.0, unit="G/C3", descr="In-situ brine case")
    las.append_curve("DT", dt_us_ft, unit="US/F", descr="Sonic slowness, in-situ brine case")
    las.append_curve("VP", df["VP_BRINE_MPS"].to_numpy(), unit="M/S")
    las.append_curve("VS", df["VS_BRINE_MPS"].to_numpy(), unit="M/S")
    las.write(str(path), version=2.0)


def main():
    print("[1/6] Building synthetic type-well log dataset ...")
    df = sw.build_synthetic_well()
    reservoir_top, reservoir_base = df.attrs["reservoir_top_m"], df.attrs["reservoir_base_m"]

    print("[2/6] Averaging representative layer properties ...")
    shale_vp, shale_vs, shale_rho = sw.reservoir_average_properties(df, "BRINE", *SHALE_CAP_ZONE)
    under_vp, under_vs, under_rho = sw.reservoir_average_properties(df, "BRINE", *UNDERLYING_SHALE_ZONE)
    reservoir_props = {}
    for fluid in ("BRINE", "OIL", "GAS"):
        vp, vs, rho = sw.reservoir_average_properties(df, fluid, *RESERVOIR_CLEAN_ZONE)
        reservoir_props[fluid] = dict(vp=vp, vs=vs, rho=rho, ai=vp * rho, vpvs=vp / vs)

    print("[3/6] Building rock physics template + core calibration samples ...")
    mid_depth = sum(RESERVOIR_CLEAN_ZONE) / 2.0
    t_mid, p_mid = fl.in_situ_conditions(mid_depth)
    rho_b, k_b = fl.brine_properties(t_mid, p_mid, sw.SALINITY_PPM)
    rho_o, k_o = fl.dead_oil_properties(t_mid, p_mid, api_gravity=sw.OIL_API)
    rho_g, k_g = fl.gas_properties(t_mid, p_mid, gas_gravity=sw.GAS_GRAVITY)

    porosity_range = np.linspace(0.05, 0.40, 60)
    template_curves = rpt.build_template_curves(
        porosity_range, sand_vshale=0.08, shale_vshale=0.95,
        brine_props=(rho_b, k_b), oil_props=(rho_o, k_o), gas_props=(rho_g, k_g))
    core_samples = rpt.synthesize_core_samples(
        26, np.linspace(0.20, 0.38, 60), sand_vshale=0.08, fluid_props=(rho_b, k_b))

    print("[4/6] Pre-stack synthetic seismic (AVO) modelling ...")
    dt_s = 0.0005
    time_axis = np.arange(1.60, 2.00 + dt_s / 2, dt_s)
    _, wavelet = avo.ricker_wavelet(RICKER_FREQUENCY_HZ, dt_s=dt_s, length_s=0.128)

    gathers, stacks, avo_points, lmr_points = {}, {}, {}, {}
    lmr_points["SHALE"] = (rpm.lambda_rho(shale_vp, shale_vs, shale_rho),
                            rpm.mu_rho(shale_vs, shale_rho))
    for fluid in ("BRINE", "OIL", "GAS"):
        p = reservoir_props[fluid]
        interfaces = [
            dict(vp1=shale_vp, vs1=shale_vs, rho1=shale_rho,
                 vp2=p["vp"], vs2=p["vs"], rho2=p["rho"], twt_s=two_way_time(reservoir_top)),
            dict(vp1=p["vp"], vs1=p["vs"], rho1=p["rho"],
                 vp2=under_vp, vs2=under_vs, rho2=under_rho, twt_s=two_way_time(reservoir_base)),
        ]
        gather, (A, B, C) = avo.build_angle_gather(interfaces, ANGLES_DEG, time_axis, wavelet)
        gathers[fluid] = gather
        stacks[fluid] = {
            "Near (0-12 deg)": avo.stack_gather(gather, ANGLES_DEG, NEAR_RANGE),
            "Mid (12-24 deg)": avo.stack_gather(gather, ANGLES_DEG, MID_RANGE),
            "Far (24-35 deg)": avo.stack_gather(gather, ANGLES_DEG, FAR_RANGE),
        }
        avo_points[fluid] = (A, B)
        reservoir_props[fluid]["avo_intercept"] = A
        reservoir_props[fluid]["avo_gradient"] = B
        reservoir_props[fluid]["avo_class"] = avo.classify_avo(A, B)
        lmr_points[fluid] = (rpm.lambda_rho(p["vp"], p["vs"], p["rho"]),
                              rpm.mu_rho(p["vs"], p["rho"]))

    print("[5/6] Rendering figures ...")
    viz.plot_log_tracks(df, reservoir_top, reservoir_base, FIGDIR / "01_log_tracks.png")
    viz.plot_depth_trends(df, reservoir_top, reservoir_base, FIGDIR / "02_depth_trends.png")
    viz.plot_rock_physics_template(df, template_curves, core_samples, reservoir_top,
                                    reservoir_base, FIGDIR / "03_rock_physics_template.png")
    viz.plot_lambda_mu_rho(lmr_points, FIGDIR / "04_lambda_mu_rho.png")
    viz.plot_vp_porosity(df, template_curves, reservoir_top, reservoir_base,
                          FIGDIR / "05_vp_porosity.png")
    viz.plot_angle_gathers(gathers, time_axis, ANGLES_DEG, FIGDIR / "06_angle_gathers.png")
    viz.plot_near_mid_far(stacks, time_axis, (1770, 1830), FIGDIR / "07_near_mid_far_stacks.png")
    viz.plot_avo_crossplot(avo_points, FIGDIR / "08_avo_crossplot.png")

    print("[6/6] Writing data products (CSV, LAS, results summary) ...")
    df.to_csv(DATADIR / "synthetic_well_logs.csv", index=False)
    write_las(df, DATADIR / "synthetic_well.las")
    core_samples.to_csv(DATADIR / "core_calibration_samples.csv", index=False)

    results = {
        "well": {
            "depth_top_m": sw.DEPTH_TOP_M, "depth_base_m": sw.DEPTH_BASE_M,
            "reservoir_top_m": reservoir_top, "reservoir_base_m": reservoir_base,
        },
        "in_situ_conditions_at_reservoir": {"temperature_c": t_mid, "pressure_mpa": p_mid / 1e6},
        "shale_cap_properties": {"vp": shale_vp, "vs": shale_vs, "rho": shale_rho},
        "underlying_shale_properties": {"vp": under_vp, "vs": under_vs, "rho": under_rho},
        "fluid_properties_at_reservoir_conditions": {
            "brine": {"rho": rho_b, "k": k_b}, "oil": {"rho": rho_o, "k": k_o},
            "gas": {"rho": rho_g, "k": k_g},
        },
        "reservoir_properties": reservoir_props,
    }
    sanity_checks(df, results)

    with open(ROOT / "results_summary.json", "w") as fh:
        json.dump(results, fh, indent=2, default=float)

    print("\n=== Reservoir sand properties by fluid case (clean interval average) ===")
    for fluid, p in reservoir_props.items():
        print(f"{fluid:6s}  Vp={p['vp']:7.1f} m/s  Vs={p['vs']:7.1f} m/s  "
              f"rho={p['rho']/1000:5.3f} g/cc  AI={p['ai']/1000:8.1f}  Vp/Vs={p['vpvs']:5.3f}  "
              f"A={p['avo_intercept']:+.3f}  B={p['avo_gradient']:+.3f}  -> {p['avo_class']}")
    print("\nDone. Figures in ./figures, data products in ./data, summary in results_summary.json")


if __name__ == "__main__":
    main()
